In [72]:
# load-data

import pandas as pd
data=pd.read_csv("C:/Users/L1F22BSDS0056/Desktop/jobs_data.csv")
data

,work_year,job_title,job_category,salary,salary_in_usd,experience_level,company_location
0,2023,Data DevOps Engineer,Data Engineering,88000.0,95012.0,Mid-level,Germany
1,2023,Data Architect,Data Architecture and Modeling,186000.0,186000.0,Senior,United States
2,2023,Data Architect,Data Architecture and Modeling,81800.0,NaN,Senior,United States
3,2023,Data Scientist,Data Science and Research,212000.0,212000.0,Senior,United States
4,2023,Data Scientist,Data Science and Research,NaN,93300.0,Senior,United States
...,...,...,...,...,...,...,...
9350,2021,Data Specialist,Data Management and Strategy,165000.0,165000.0,Senior,United States
9351,2020,Data Scientist,Data Science and Research,412000.0,412000.0,Senior,United States
9352,2021,Principal Data Scientist,Data Science and Research,151000.0,151000.0,Mid-level,United States
9353,2020,Data Scientist,Data Science and Research,105000.0,105000.0,Entry-level,United States
9354,2020,Business Data Analyst,Data Analysis,100000.0,100000.0,Entry-level,United States

In [73]:
# Define-Head

data.head(10)

,work_year,job_title,job_category,salary,salary_in_usd,experience_level,company_location
0,2023,Data DevOps Engineer,Data Engineering,88000.0,95012.0,Mid-level,Germany
1,2023,Data Architect,Data Architecture and Modeling,186000.0,186000.0,Senior,United States
2,2023,Data Architect,Data Architecture and Modeling,81800.0,NaN,Senior,United States
3,2023,Data Scientist,Data Science and Research,212000.0,212000.0,Senior,United States
4,2023,Data Scientist,Data Science and Research,NaN,93300.0,Senior,United States
5,2023,Data Scientist,Data Science and Research,130000.0,130000.0,Senior,United States
6,2023,Data Scientist,Data Science and Research,NaN,100000.0,Senior,United States
7,2023,Machine Learning Researcher,Machine Learning and AI,224400.0,224400.0,Mid-level,United States
8,2023,Machine Learning Researcher,Machine Learning and AI,138700.0,138700.0,Mid-level,United States
9,2023,Data Engineer,Data Engineering,210000.0,210000.0,Executive,United States

In [74]:
#Data-information

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9355 entries, 0 to 9354
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   work_year         9355 non-null   int64
 1   job_title         9355 non-null   object
 2   job_category      9355 non-null   object
 3   salary            9353 non-null   float64
 4   salary_in_usd     9354 non-null   float64
 5   experience_level  9355 non-null   object
 6   company_location  9355 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 511.7+ KB

In [75]:
#Null and sum all data

data.isnull().sum()

work_year           0
job_title           0
job_category        0
salary              2
salary_in_usd       1
experience_level    0
company_location    0
dtype: int64

In [76]:
#Distribution of Values

data.describe().astype(int)

       work_year  salary  salary_in_usd
count       9355    9353           9354
mean        2022  149939         150306
std            0   63610          63176
min         2020   14000          15000
25%         2023  105200         105700
50%         2023  143860         143050
75%         2023  187000         186784
max         2023  450000         450000

In [77]:
#Value Counts

data.head(20)['experience_level'].value_counts()

Senior         10
Mid-level       6
Executive       2
Entry-level     2
Name: experience_level, dtype: int64

In [124]:
#Data-Manipulation


#Drop columns
drop=data.drop('job_category',axis=1)
print("\nAfter drop column:-\n",drop)

#Fill mising value
fill=data['salary'].fillna(150000)
print("\nAfter fill missing value:-\n",fill)

#Drop rows
dropna=data.dropna()
print("\nAfter drop uncomplete rows:-\n",dropna)

#Sorting
sort=np.sort(data['work_year'])
print("\nAfter sorting work_year column:-\n",sort)

After drop column:-
       work_year  job_title    salary  salary_in_usd  experience_level  \
0          2023         42   88000.0        95012.0                 2
1          2023         41  186000.0       186000.0                 3
2          2023         41   81800.0            NaN                 3
3          2023         69  212000.0       212000.0                 3
4          2023         69       NaN        93300.0                 3
...         ...        ...       ...            ...               ...
9350       2021         71  165000.0       165000.0                 3
9351       2020         69  412000.0       412000.0                 3
9352       2021        114  151000.0       151000.0                 2
9353       2020         69  105000.0       105000.0                 0
9354       2020         21  100000.0       100000.0                 0

      company_location
0                   23
1                   69
2                   69
3                   69
4                   69
...                ...
9350                69
9351                69
9352                69
9353                69
9354                69

[9355 rows x 6 columns]

After fill missing value:-
 0        88000.0
1       186000.0
2        81800.0
3       212000.0
4       150000.0
          ...
9350    165000.0
9351    412000.0
9352    151000.0
9353    105000.0
9354    100000.0
Name: salary, Length: 9355, dtype: float64

After drop uncomplete rows:-
       work_year  job_title  job_category    salary  salary_in_usd  \
0          2023         42             4   88000.0        95012.0
1          2023         41             3  186000.0       186000.0
3          2023         69             7  212000.0       212000.0
5          2023         69             7  130000.0       130000.0
7          2023        102             9  224400.0       224400.0
...         ...        ...           ...       ...            ...
9350       2021         71             5  165000.0       165000.0
9351       2020         69             7  412000.0       412000.0
9352       2021        114             7  151000.0       151000.0
9353       2020         69             7  105000.0       105000.0
9354       2020         21             2  100000.0       100000.0

      experience_level  company_location
0                    2                23
1                    3                69
3                    3                69
5                    3                69
7                    2                69
...                ...               ...
9350                 3                69
9351                 3                69
9352                 2                69
9353                 0                69
9354                 0                69

[9352 rows x 7 columns]

After sorting work_year column:-
 [2020 2020 2020 ... 2023 2023 2023]

In [48]:
#Normalization

data['salary']=((data['salary']-data['salary'].min())/(data['salary'].max()-data['salary'].min()))
print("After Normalized-Data:-\n",data['salary'])

After Normalized-Data:-
 0       0.169725
1       0.394495
2       0.155505
3       0.454128
4       0.181881
          ...
9350    0.346330
9351    0.912844
9352    0.314220
9353    0.208716
9354    0.197248
Name: salary, Length: 9355, dtype: float64

In [104]:
#Variance
variance=data['salary_in_usd'].var()
print("Variance of salary_in_usd column : ",variance)

#Standard-deviation
standard_deviation=data['salary_in_usd'].std()
print("Standard-deviation of salary_in_usd column : ",standard_deviation)

Variance of salary_in_usd column :  3991305354.391401
Standard-deviation of salary_in_usd column :  63176.77860093375

In [ ]:
#Statical-Analysis
import numpy as np

#Mean
mean=np.mean(data.head(20)['salary'])
print("Average of salary : ",mean) 

#Mode
mode=np.argmax(np.bincount(data.head(20)['salary_in_usd']))
print("\nMost repeated values in salary_in_usd column : ",mode)

#Median
sort=np.sort(data.head(20)['salary_in_usd'])
median=np.median(data.head(20)['salary_in_usd'])
print("\nAfter Sorted-data :-\n",sort)
print("\nMedian of salary_in_usd column : ",median)

In [109]:
#Machine-Learning

#Data-Preprocessing
from sklearn.preprocessing import LabelEncoder

df=pd.DataFrame(data)
print(df)
job_title=LabelEncoder()  
job_category=LabelEncoder()
experience_level=LabelEncoder()
company_location=LabelEncoder()

df['job_title']=job_title.fit_transform(df['job_title'])
df['job_category']=job_category.fit_transform(df['job_category'])
df['experience_level']=experience_level.fit_transform(df['experience_level'])
df['company_location']=company_location.fit_transform(df['company_location'])

print("\nAfter preprocessing:-\n",df)

      work_year  job_title  job_category    salary  salary_in_usd  \
0          2023         42             4   88000.0        95012.0
1          2023         41             3  186000.0       186000.0
2          2023         41             3   81800.0            NaN
3          2023         69             7  212000.0       212000.0
4          2023         69             7       NaN        93300.0
...         ...        ...           ...       ...            ...
9350       2021         71             5  165000.0       165000.0
9351       2020         69             7  412000.0       412000.0
9352       2021        114             7  151000.0       151000.0
9353       2020         69             7  105000.0       105000.0
9354       2020         21             2  100000.0       100000.0

      experience_level  company_location
0                    2                23
1                    3                69
2                    3                69
3                    3                69
4                    3                69
...                ...               ...
9350                 3                69
9351                 3                69
9352                 2                69
9353                 0                69
9354                 0                69

[9355 rows x 7 columns]

After preprocessing:-
       work_year  job_title  job_category    salary  salary_in_usd  \
0          2023         42             4   88000.0        95012.0
1          2023         41             3  186000.0       186000.0
2          2023         41             3   81800.0            NaN
3          2023         69             7  212000.0       212000.0
4          2023         69             7       NaN        93300.0
...         ...        ...           ...       ...            ...
9350       2021         71             5  165000.0       165000.0
9351       2020         69             7  412000.0       412000.0
9352       2021        114             7  151000.0       151000.0
9353       2020         69             7  105000.0       105000.0
9354       2020         21             2  100000.0       100000.0

      experience_level  company_location
0                    2                23
1                    3                69
2                    3                69
3                    3                69
4                    3                69
...                ...               ...
9350                 3                69
9351                 3                69
9352                 2                69
9353                 0                69
9354                 0                69

[9355 rows x 7 columns]

In [ ]:
#Split data into training and testing sets

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score

X=df['salary']
y=df['salary_in_usd']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
model=DecisionTreeClassifier()
model.fit(X_train,y_train)
pred=model.predict(X_test)
accuracy=accuracy_score(y_test,pred)
precision=precision_score(y_test,pred,pos_label='yes')
recall=recall_score(y_test,pred,pos_label='yes')

print(f"\nAccuracy : {accuracy:.2f}")
print(f"\nPrecision : {precision:.2f}")
print(f"\nRecall : {recall:.2f}")

In [ ]:
#Data-Visualizatio

#Histogram
import matplotlib.pyplot as plt
plt.figure(figsize=(8,7))
plt.hist(df['salary'],color='purple',edgecolor='black',bins=8)
plt.title("Histogram Graph")
plt.xlabel("Salary")
plt.ylabel("Time periods")
plt.show()

In [ ]:
#Pie_chart
experience=df['experience_level'].value_counts()
plt.figure(figsize=(8,8))
plt.pie(experience,autopct='%1.1f%%',colors=['lightblue','violet','purple','yellow'])
plt.title("Pie-Chart Graph")
plt.show()

In [ ]:
#Scatter
plt.hist(df['salary'],color='purple',edgecolor='black',bins=8)
plt.title("Histogram Graph")
plt.xlabel("Salary")
plt.ylabel("Time periods")
plt.show()
plt.scatter(df.head(20)['work_year'] ,df.head(20)['salary'],color='blue',alpha=0.8)
plt.title("Scatter-graph")
plt.xlabel("work_year")
plt.ylabel("salary")
plt.show()

In [ ]:
#Line_graph

plt.figure(figsize=(8,6))
plt.plot(df.head(20)['salary'],df.head(20)['salary_in_usd'],marker='o',linestyle='-',color='green')
plt.title("Line Graph")
plt.xlabel("job_category")
plt.ylabel("experience_level")
plt.show()